In [21]:
#following are the libraries 
import numpy as np  # to perform a wide variety of mathematical operations on arrays.
import pandas as pd # comman lib and use for displaying dataframe 
import tweepy       #gives you a very convenient way to access the Twitter API with Python
import re          #provides support for Perl-like regular expressions in Python.
import matplotlib.pyplot as plt # data visualization and graphical plotting library for Python 
plt.style.use('fivethirtyeight') # type of graps
pd.set_option('display.max_colwidth', -1)
import datetime

C:\Users\patel\AppData\Local\Temp\ipykernel_7784\317671732.py:8: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  pd.set_option('display.max_colwidth', -1)

Calling Keys of Twitter API

In [2]:
%run ./keys.ipynb  # runs Jupyter Notebook files

In [3]:
auth = tweepy.OAuthHandler(consumer_key, consumer_secret) # auth giving a user permissions to access a particular resource.
auth.set_access_token(access_token,access_token_secret)
api = tweepy.API(auth , wait_on_rate_limit= True) #open source Python package to access the Twitter API with Python

In [4]:
api = tweepy.API(auth)
api = tweepy.API(auth, wait_on_rate_limit=True)

In [5]:
tweets = []
likes = []
time = []

search_term = '#Bitcoin'
 #Create a cursor 
    
for i in tweepy.Cursor(api.search_tweets, q= search_term, lang='en',until="2022-07-20", tweet_mode='extended').items(100):
    tweets.append(i.full_text)
    likes.append(i.favorite_count)
    time.append(i.created_at)
    
# just for 2000 tweets for now 

#store tweets in variable
#all_tweets= [tweet.full_text for tweet in tweets]

In [6]:
df= pd.DataFrame({'tweets':tweets, 'likes':likes, 'time':time})

In [7]:
pd.set_option('display.max_colwidth', None)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87908 entries, 0 to 87907
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   tweets  87908 non-null  object
 1   likes   87908 non-null  object
 2   time    87908 non-null  object
dtypes: object(3)
memory usage: 2.0+ MB

In [9]:
df.to_csv('Bitcooin6.csv')

In [26]:
from pyspark import F


file0 = "C:\\Users\\patel\\Downloads\\project\\crypto.csv"
file1 = "C:\\Users\\patel\\Downloads\\project\\crypto1.csv"
file2 = "C:\\Users\\patel\\Downloads\\project\\crypto2.csv"
file3 = "C:\\Users\\patel\\Downloads\\project\\crypto3.csv"
file4 = "C:\\Users\\patel\\Downloads\\project\\crypto4.csv"
file5 = "C:\\Users\\patel\\Downloads\\project\\crypto5.csv"
file6 = "C:\\Users\\patel\\Downloads\\project\\crypto6.csv"
file7 = "C:\\Users\\patel\\Downloads\\project\\crypto7.csv"
file8 = "C:\\Users\\patel\\Downloads\\project\\crypto8.csv"
file9 = "C:\\Users\\patel\\Downloads\\project\\crypto9.csv"
file12 = "C:\\Users\\patel\\Downloads\\project\\Bitcooin.csv"
file13 = "C:\\Users\\patel\\Downloads\\project\\Bitcooin6.csv"
file14 = "C:\\Users\\patel\\Downloads\\project\\Bitcooin7.csv"
file15 = "C:\\Users\\patel\\Downloads\\project\\Bitcooin8.csv"
file16 = "C:\\Users\\patel\\Downloads\\project\\Bitcooin11.csv"

In [27]:
df = pd.concat(
   map(pd.read_csv, [file0,file1, file2,file3,file4,file5,file6,file7,file8,file9,file12,file13,file14,file15,file16]), ignore_index=True)

In [28]:
df

,Unnamed: 0,tweets,likes,time
0,0,RT @MARBLEXofficial: MBX with Consensus 2022âœ¨ Presents #Marblex Giveaway Event! Please check the detailsðŸ”¥\nðŸ“†Event Period : June 9th to 12thâ€¦,0,2022-06-10 23:59:59+00:00
1,1,Aside of #crypto itâ€™s getting real out here the gas the food on the table the bills going up they out here sucking us dry of every dollar I got kids and a wife to take care of fr got me over here thinking man #economy #recession #America,2,2022-06-10 23:59:56+00:00
2,2,"RT @OfficialTravlad: I will send $1,000 to someone that retweets and is following @rovercrc and myself in the next 48hrs.\n\nHe is also givinâ€¦",0,2022-06-10 23:59:51+00:00
3,3,RT @lisaownet: Thanks for the socks.\n\nMeet me at #Consensus2022 to discuss #Web3 #tokenization #tokenomics #blockchain #cryptocurrency #cryâ€¦,0,2022-06-10 23:59:50+00:00
4,4,RT @metavisa: We are very excited to announce that $MESA will be available on @gate_io on June 12th\n\n$MESA is growing daily and we can't waâ€¦,0,2022-06-10 23:59:49+00:00
...,...,...,...,...
128003,9995,RT @BitcoinMagazine: NEW: Protests escalate in China as millions can't withdraw money from their bank accounts since April.\n\nðŸ‡¨ðŸ‡³ needs #Bitcâ€¦,0,2022-07-11 21:14:27+00:00
128004,9996,RT @AurelienOhayon: #BITCOIN IS READY FOR A MASSIVE BULL RUN. https://t.co/zz6Bm0C7fJ,0,2022-07-11 21:14:27+00:00
128005,9997,"ðŸ’µ4,453 #BTC (92,864,330 USD) move from unknown wallet to unknown wallet\n \nDate : 2022-07-11 21:12:50 (GMT 0)\nBlockchain : #BITCOIN\nSymbol : #BTC\n \nDetail: https://t.co/z1Su1xRQxB",0,2022-07-11 21:14:26+00:00
128006,9998,"ðŸ’µ4,453 #BTC (92,863,816 USD) move from unknown wallet to unknown wallet\n \nDate : 2022-07-11 21:12:50 (GMT 0)\nBlockchain : #BITCOIN\nSymbol : #BTC\n \nDetail: https://t.co/TGv2cDHLXV",0,2022-07-11 21:14:25+00:00
128007,9999,RT @BitcoinMagazine: JUST IN: Another spot #bitcoin ETN will launch in Germany today ðŸ‡©ðŸ‡ª\n\nStill none in the ðŸ‡ºðŸ‡¸...,0,2022-07-11 21:14:24+00:00

In [29]:
df.to_csv('Proect_dataset.csv')

In [30]:
df.head(5)
df

,Unnamed: 0,tweets,likes,time
0,0,RT @MARBLEXofficial: MBX with Consensus 2022âœ¨ Presents #Marblex Giveaway Event! Please check the detailsðŸ”¥\nðŸ“†Event Period : June 9th to 12thâ€¦,0,2022-06-10 23:59:59+00:00
1,1,Aside of #crypto itâ€™s getting real out here the gas the food on the table the bills going up they out here sucking us dry of every dollar I got kids and a wife to take care of fr got me over here thinking man #economy #recession #America,2,2022-06-10 23:59:56+00:00
2,2,"RT @OfficialTravlad: I will send $1,000 to someone that retweets and is following @rovercrc and myself in the next 48hrs.\n\nHe is also givinâ€¦",0,2022-06-10 23:59:51+00:00
3,3,RT @lisaownet: Thanks for the socks.\n\nMeet me at #Consensus2022 to discuss #Web3 #tokenization #tokenomics #blockchain #cryptocurrency #cryâ€¦,0,2022-06-10 23:59:50+00:00
4,4,RT @metavisa: We are very excited to announce that $MESA will be available on @gate_io on June 12th\n\n$MESA is growing daily and we can't waâ€¦,0,2022-06-10 23:59:49+00:00
...,...,...,...,...
128003,9995,RT @BitcoinMagazine: NEW: Protests escalate in China as millions can't withdraw money from their bank accounts since April.\n\nðŸ‡¨ðŸ‡³ needs #Bitcâ€¦,0,2022-07-11 21:14:27+00:00
128004,9996,RT @AurelienOhayon: #BITCOIN IS READY FOR A MASSIVE BULL RUN. https://t.co/zz6Bm0C7fJ,0,2022-07-11 21:14:27+00:00
128005,9997,"ðŸ’µ4,453 #BTC (92,864,330 USD) move from unknown wallet to unknown wallet\n \nDate : 2022-07-11 21:12:50 (GMT 0)\nBlockchain : #BITCOIN\nSymbol : #BTC\n \nDetail: https://t.co/z1Su1xRQxB",0,2022-07-11 21:14:26+00:00
128006,9998,"ðŸ’µ4,453 #BTC (92,863,816 USD) move from unknown wallet to unknown wallet\n \nDate : 2022-07-11 21:12:50 (GMT 0)\nBlockchain : #BITCOIN\nSymbol : #BTC\n \nDetail: https://t.co/TGv2cDHLXV",0,2022-07-11 21:14:25+00:00
128007,9999,RT @BitcoinMagazine: JUST IN: Another spot #bitcoin ETN will launch in Germany today ðŸ‡©ðŸ‡ª\n\nStill none in the ðŸ‡ºðŸ‡¸...,0,2022-07-11 21:14:24+00:00

In [31]:
del df['Unnamed: 0']

In [32]:
df.to_csv('Proect_dataset.csv')

In [17]:
df.to_csv('Proect_dataset.csv')

In [33]:
df

,tweets,likes,time
0,RT @MARBLEXofficial: MBX with Consensus 2022âœ¨ Presents #Marblex Giveaway Event! Please check the detailsðŸ”¥\nðŸ“†Event Period : June 9th to 12thâ€¦,0,2022-06-10 23:59:59+00:00
1,Aside of #crypto itâ€™s getting real out here the gas the food on the table the bills going up they out here sucking us dry of every dollar I got kids and a wife to take care of fr got me over here thinking man #economy #recession #America,2,2022-06-10 23:59:56+00:00
2,"RT @OfficialTravlad: I will send $1,000 to someone that retweets and is following @rovercrc and myself in the next 48hrs.\n\nHe is also givinâ€¦",0,2022-06-10 23:59:51+00:00
3,RT @lisaownet: Thanks for the socks.\n\nMeet me at #Consensus2022 to discuss #Web3 #tokenization #tokenomics #blockchain #cryptocurrency #cryâ€¦,0,2022-06-10 23:59:50+00:00
4,RT @metavisa: We are very excited to announce that $MESA will be available on @gate_io on June 12th\n\n$MESA is growing daily and we can't waâ€¦,0,2022-06-10 23:59:49+00:00
...,...,...,...
128003,RT @BitcoinMagazine: NEW: Protests escalate in China as millions can't withdraw money from their bank accounts since April.\n\nðŸ‡¨ðŸ‡³ needs #Bitcâ€¦,0,2022-07-11 21:14:27+00:00
128004,RT @AurelienOhayon: #BITCOIN IS READY FOR A MASSIVE BULL RUN. https://t.co/zz6Bm0C7fJ,0,2022-07-11 21:14:27+00:00
128005,"ðŸ’µ4,453 #BTC (92,864,330 USD) move from unknown wallet to unknown wallet\n \nDate : 2022-07-11 21:12:50 (GMT 0)\nBlockchain : #BITCOIN\nSymbol : #BTC\n \nDetail: https://t.co/z1Su1xRQxB",0,2022-07-11 21:14:26+00:00
128006,"ðŸ’µ4,453 #BTC (92,863,816 USD) move from unknown wallet to unknown wallet\n \nDate : 2022-07-11 21:12:50 (GMT 0)\nBlockchain : #BITCOIN\nSymbol : #BTC\n \nDetail: https://t.co/TGv2cDHLXV",0,2022-07-11 21:14:25+00:00
128007,RT @BitcoinMagazine: JUST IN: Another spot #bitcoin ETN will launch in Germany today ðŸ‡©ðŸ‡ª\n\nStill none in the ðŸ‡ºðŸ‡¸...,0,2022-07-11 21:14:24+00:00